### ISSUE TITLE
question about flavor

### ISSUE THREAD

**Issue by hubutui** [ropensci-org/cranchecksdocs#21]
Hi, I'm using `https://cranchecks.info/pkgs/{pkgname}` to check for pkg update from CRAN. I'm confused about what `flavor` means in the return json data. For example, `r-devel-linux-x86_64-debian-clang` means this pkg is build in Debian x86_64 with clang compiler, am I right? Actually, I only care about the latest version of the pkg. But I'm not sure if version differs if flavor differs.

**Comment by hubutui** [comment]
BTW, I'm also looking for an API to check pkg update from https://www.bioconductor.org/, are you aware of any similar API?

**Comment by maelle** [comment]
@hubutui flavor correspond to https://cran.r-project.org/web/checks/check_flavors.html cf https://blog.r-hub.io/2019/04/25/r-devel-linux-x86-64-debian-clang/#cran-checks-101  Does this help?

**Comment by hubutui** [comment]
thx, I'm using https://cran.r-project.org/src/contrib/PACKAGES instead, bioconductor also provides the same metadata.

**Comment by maelle** [comment]
Oh now I understand your question, you want to follow package updates, not checks data at all!

Relevant services for CRAN:

* [CRANberries](http://dirk.eddelbuettel.com/cranberries/index.html)
* [CRANalerts](https://deanattali.com/blog/cranalerts/)
* [pkgsearch](http://r-hub.github.io/pkgsearch/reference/index.html#section-get-cran-releases-archivals)

For Bioconductor, I do not know what is available.
